//! One unit test per JSONTestSuite `test_parsing` file (generated by `build.rs`).

use crate::{DefaultHandler, Parser};

#[derive(Clone, Copy)]
enum Expect {
    Pass,
    Fail,
    Either,
}

fn try_parse(bytes: &[u8]) -> Result<(), String> {
    let mut handler = DefaultHandler;
    let mut parser = Parser::new(&mut handler);
    parser.disable_all_limits();
    let mut data = bytes;
    parser.receive(&mut data).map_err(|e| e.to_string())?;
    parser.close().map_err(|e| e.to_string())
}

fn run_case(path: &str, expect: Expect) {
    let bytes = std::fs::read(path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    let result = try_parse(&bytes);
    let name = std::path::Path::new(path)
        .file_name()
        .and_then(|n| n.to_str())
        .unwrap_or(path);

    match expect {
        Expect::Pass => {
            if let Err(e) = result {
                panic!("{name}: expected pass, got error: {e}");
            }
        }
        Expect::Fail => {
            if result.is_ok() {
                panic!("{name}: expected fail, but parsed OK");
            }
        }
        Expect::Either => {}
    }
}

include!(concat!(env!("OUT_DIR"), "/json_test_suite_cases.rs"));
